name: Pages

on:
  push:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install -g tiddlywiki
      - name: Configure wiki readonly
        run: |
            cp config_deploy/* wiki/tiddlers
            rm wiki/tiddlers/\$__New\ inequality\ button.tid
      - name: Build
        run: tiddlywiki wiki --build index
      - name: build html
        run: tiddlywiki wiki --rendertiddler $:/core/save/all ../../public/index.html text/plain
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./public
