
name: Create wiki

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-node@v2
    - run: npm install -g tiddlywiki
    - run: tiddlywiki docs --build index  
